#!/usr/bin/env python3
"""Extract canonical SignSaarthi keypoint JSON from local INCLUDE/iSign videos.

This script intentionally stores normalized landmarks only. It does not copy or
embed raw video frames in the output artifact.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import tempfile
import zipfile
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--metadata", required=True, help="INCLUDE metadata JSON generated by fetch-include-metadata.ts")
    parser.add_argument("--video-root", help="Root directory containing extracted raw videos")
    parser.add_argument("--zip-archive", help="Zip archive containing videos; records are extracted one at a time")
    parser.add_argument("--output", required=True, help="Canonical keypoint sequence JSON output path")
    parser.add_argument("--split", action="append", default=[], help="Restrict to split; repeatable")
    parser.add_argument("--limit", type=int, default=0, help="Maximum videos to process")
    parser.add_argument("--dataset-id", default="include", choices=["include", "isign", "curated_mvp"])
    parser.add_argument("--frame-stride", type=int, default=2)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.frame_stride < 1:
        raise SystemExit("--frame-stride must be at least 1")

    try:
        import cv2  # type: ignore
        import mediapipe as mp  # type: ignore
    except ImportError as exc:
        raise SystemExit(
            "Missing Python dependency. Install with: python3 -m pip install mediapipe opencv-python"
        ) from exc

    metadata = json.loads(Path(args.metadata).read_text())
    splits = set(args.split)
    if not args.video_root and not args.zip_archive:
        raise SystemExit("Provide either --video-root or --zip-archive")

    video_root = Path(args.video_root) if args.video_root else None
    zip_archive = Path(args.zip_archive) if args.zip_archive else None
    records = [
        record
        for record in metadata.get("records", [])
        if (not splits or record.get("split") in splits) and record.get("videoPath")
    ]
    if args.limit:
        records = records[: args.limit]

    holistic = mp.solutions.holistic.Holistic(
        static_image_mode=False,
        model_complexity=1,
        enable_segmentation=False,
        refine_face_landmarks=False,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5,
    )

    sequences: list[dict[str, Any]] = []
    missing_videos: list[str] = []
    if zip_archive:
        with zipfile.ZipFile(zip_archive) as archive:
            names = set(archive.namelist())
            for record in records:
                relative_path = str(record["videoPath"]).replace("\\", "/")
                archive_name = find_archive_name(relative_path, names)
                if not archive_name:
                    missing_videos.append(relative_path)
                    continue
                with tempfile.TemporaryDirectory(prefix="signsaarthi-keypoints-") as temp_dir:
                    temp_path = Path(temp_dir) / Path(relative_path).name
                    with archive.open(archive_name) as source, temp_path.open("wb") as target:
                        target.write(source.read())
                    sequence = extract_sequence(cv2, holistic, temp_path, record, args.dataset_id, args.frame_stride, relative_path)
                    if sequence["frames"]:
                        sequences.append(sequence)
    else:
        assert video_root is not None
        for record in records:
            relative_path = str(record["videoPath"]).replace("\\", "/")
            video_path = video_root / relative_path
            if not video_path.exists():
                candidates = list(video_root.rglob(Path(relative_path).name))
                video_path = candidates[0] if candidates else video_path
            if not video_path.exists():
                missing_videos.append(relative_path)
                continue

            sequence = extract_sequence(cv2, holistic, video_path, record, args.dataset_id, args.frame_stride, relative_path)
            if sequence["frames"]:
                sequences.append(sequence)

    holistic.close()
    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(sequences, indent=2) + "\n")
    print(f"Extracted {len(sequences)} keypoint sequence(s) to {output_path}")
    if missing_videos:
        print(f"Skipped {len(missing_videos)} missing video(s); first missing: {missing_videos[0]}")


def extract_sequence(
    cv2: Any,
    holistic: Any,
    video_path: Path,
    record: dict[str, Any],
    dataset_id: str,
    frame_stride: int,
    source_id: str,
) -> dict[str, Any]:
    capture = cv2.VideoCapture(str(video_path))
    reported_fps = float(capture.get(cv2.CAP_PROP_FPS) or 0)
    source_fps = reported_fps if math.isfinite(reported_fps) and reported_fps > 0 else 25.0
    frame_index = 0
    frames: list[dict[str, Any]] = []
    attempted = 0
    missing = 0

    while True:
        ok, frame = capture.read()
        if not ok:
            break
        if frame_index % frame_stride != 0:
            frame_index += 1
            continue

        attempted += 1
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        result = holistic.process(rgb)
        landmarks = collect_landmarks(result)
        if not landmarks:
            missing += 1
        else:
            timestamp_ms = float(capture.get(cv2.CAP_PROP_POS_MSEC) or 0)
            fallback_timestamp_ms = (frame_index / source_fps) * 1000
            if (
                not math.isfinite(timestamp_ms)
                or timestamp_ms < 0
                or (frame_index > 0 and timestamp_ms == 0)
                or (frames and timestamp_ms <= float(frames[-1]["timestampMs"]))
            ):
                timestamp_ms = fallback_timestamp_ms
            frames.append(
                {
                    "timestampMs": round(timestamp_ms, 3),
                    "landmarks": landmarks,
                }
            )
        frame_index += 1

    capture.release()
    timing = derive_effective_timing(frames, source_fps, frame_stride)
    digest = hashlib.sha256(source_id.encode("utf-8")).hexdigest()[:16]
    label = str(record.get("label") or video_path.stem)
    sequence = {
        "sampleId": f"{dataset_id}_{record.get('split', 'train')}_{digest}",
        "label": label,
        "gloss": normalize_gloss(label),
        "datasetId": dataset_id,
        "split": record.get("split", "train"),
        "fps": timing["fps"],
        "durationMs": timing["durationMs"],
        "sourceFps": round(source_fps, 6),
        "frameStride": frame_stride,
        "timingSource": timing["timingSource"],
        "extractorVersion": "signsaarthi-mediapipe-holistic-v2",
        "missingKeypointRatio": round(missing / attempted, 6) if attempted else 1,
        "checksum": sha256_file(video_path),
        "license": "Source dataset license applies; raw video not stored in this artifact",
        "frames": frames,
    }
    signer_hash = str(record.get("signerHash") or "").strip()
    if signer_hash:
        sequence["signerHash"] = signer_hash
    return sequence


def derive_effective_timing(
    frames: list[dict[str, Any]], source_fps: float, frame_stride: int
) -> dict[str, float | str]:
    """Derive playback timing from retained frame timestamps after sampling."""

    fallback_fps = source_fps / max(1, frame_stride)
    if len(frames) < 2:
        return {
            "fps": round(fallback_fps, 6),
            "durationMs": 0.0,
            "timingSource": "single-retained-frame-fallback",
        }

    timestamps = [float(frame["timestampMs"]) for frame in frames]
    if any(not math.isfinite(timestamp) for timestamp in timestamps):
        raise ValueError("Retained frame timestamps must be finite.")
    if any(current <= previous for previous, current in zip(timestamps, timestamps[1:])):
        raise ValueError("Retained frame timestamps must be strictly increasing.")

    duration_ms = timestamps[-1] - timestamps[0]
    effective_fps = ((len(timestamps) - 1) * 1000.0) / duration_ms
    return {
        "fps": round(effective_fps, 6),
        "durationMs": round(duration_ms, 3),
        "timingSource": "retained-frame-timestamps",
    }


def find_archive_name(relative_path: str, archive_names: set[str]) -> str | None:
    normalized = relative_path.replace("\\", "/")
    if normalized in archive_names:
        return normalized
    suffix = f"/{normalized}"
    matches = [name for name in archive_names if name.endswith(suffix)]
    return matches[0] if matches else None


def collect_landmarks(result: Any) -> list[dict[str, Any]]:
    landmarks: list[dict[str, Any]] = []
    append_landmark_list(landmarks, "pose", result.pose_landmarks, max_points=33)
    append_landmark_list(landmarks, "left_hand", result.left_hand_landmarks, max_points=21)
    append_landmark_list(landmarks, "right_hand", result.right_hand_landmarks, max_points=21)
    return landmarks


def append_landmark_list(target: list[dict[str, Any]], part: str, landmark_list: Any, max_points: int) -> None:
    if not landmark_list:
        return
    for index, landmark in enumerate(landmark_list.landmark[:max_points]):
        target.append(
            {
                "part": part,
                "index": index,
                "x": round(float(landmark.x), 8),
                "y": round(float(landmark.y), 8),
                "z": round(float(getattr(landmark, "z", 0.0)), 8),
                "visibility": round(float(getattr(landmark, "visibility", 1.0)), 6),
            }
        )


def normalize_gloss(label: str) -> str:
    stem = label.rsplit(".", 1)[0]
    stem = "".join(" " if character in "_-" else character for character in stem)
    return " ".join(stem.split()).upper()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return f"sha256:{digest.hexdigest()}"


if __name__ == "__main__":
    main()
